This is the jupiter notebook that Zhou writes some test functions

In [1]:
import numpy as np
import scipy

In [2]:
import numpy as np

n = 5
Q = np.random.rand(n, n)
Q = np.dot(Q, Q.T)  # Making Q symmetric to ensure it's positive semi-definite
q = np.random.rand(n)
x = np.random.rand(n)

def test_func(x):
    val = 0.5 * np.dot(x.T, np.dot(Q, x)) + np.dot(q.T, x)
    val = val.ravel()[0]
    return val

def test_func_grad(x):
    grad = np.dot(Q, x) + q
    grad = grad.ravel() 
    return grad

def test_func_hess(x):
    return Q


test_func_val = test_func(x)
test_func_grad_val = test_func_grad(x)
test_func_hess_val = test_func_hess(x)

print("test_func_val: \n", test_func_val)
print("test_func_grad_val: \n", test_func_grad_val)
print("test_func_hess_val: \n", test_func_hess_val)



test_func_val: 
 7.038824046595592
test_func_grad_val: 
 [4.43842012 2.13007518 2.81552168 5.20505467 4.64008349]
test_func_hess_val: 
 [[2.04260149 0.76979615 1.21756508 1.08151568 1.12613924]
 [0.76979615 0.48963149 0.27547615 0.65241444 0.61787782]
 [1.21756508 0.27547615 1.31443081 0.79625763 0.63283644]
 [1.08151568 0.65241444 0.79625763 2.22067753 1.84243191]
 [1.12613924 0.61787782 0.63283644 1.84243191 1.78172093]]


In [10]:
from algo_methods import *
def gradient_descent(f, f_grad, x_init, line_search_method = 'armijo', tao = 0.5, c1 = 1e-4, c2=0.9, threshold = 1e-9, max_iter = 1000):
    x_curr = x_init
    for i in range(max_iter):
        p_curr = -f_grad(x_curr)
        alpha = 1.0
        if line_search_method == 'armijo':
            alpha = armijo_line_search(f, f_grad, x_curr, tao, c1)
        elif line_search_method == 'wolfe':
            alpha = wolfe_line_search(f, f_grad, x_curr, p_curr, c1, c2)
        x_curr = x_curr + alpha * p_curr
        if np.linalg.norm(f_grad(x_curr)) < threshold:
            break
    return x_curr, f(x_curr)

x, f = gradient_descent(test_func, test_func_grad, x, 0.01, 1000)
print("x: \n", x)
print("f: \n", f)

x: 
 [nan nan nan nan nan]
f: 
 nan


In [25]:
from algo_methods import *


def Newton_CG_method(f, f_grad, f_hessian, x0, line_search_type='wolfe', tol=1e-2, 
                     max_iteration=100, c1=0.0001, c2=0.9, eta=0.01):
    

    


IndentationError: expected an indented block (3931158593.py, line 8)