This is the jupiter notebook that Zhou writes some test functions

In [1]:
import numpy as np
import scipy

In [8]:
import numpy as np

n = 5
Q = np.random.rand(n, n)
Q = np.dot(Q, Q.T)  # Making Q symmetric to ensure it's positive semi-definite
q = np.random.rand(n)
x = np.random.rand(n)

def test_func(x):
    val = 0.5 * np.dot(x.T, np.dot(Q, x)) + np.dot(q.T, x)
    val = val.ravel()[0]
    return val

def test_func_grad(x):
    grad = np.dot(Q, x) + q
    grad = grad.ravel() 
    return grad

def test_func_hess(x):
    return Q


test_func_val = test_func(x)
test_func_grad_val = test_func_grad(x)
test_func_hess_val = test_func_hess(x)

print("test_func_val: \n", test_func_val)
print("test_func_grad_val: \n", test_func_grad_val)
print("test_func_hess_val: \n", test_func_hess_val)



test_func_val: 
 4.945001319444042
test_func_grad_val: 
 [5.08411671 3.14113769 2.4350387  2.9669255  4.12976392]
test_func_hess_val: 
 [[2.5948674  1.50611307 1.29359801 1.35762705 2.17204045]
 [1.50611307 0.95865671 0.69628207 0.66211846 1.30708042]
 [1.29359801 0.69628207 1.0214591  0.40185289 1.06715744]
 [1.35762705 0.66211846 0.40185289 1.43288339 1.09011586]
 [2.17204045 1.30708042 1.06715744 1.09011586 2.08498899]]
